### ISSUE TITLE
Built this exactly like instructions

### ISSUE THREAD

**Issue by jeffbrown57** [BegoonLab/xiao-esp32c6-wifi-sensor#10]
using a seeed-studio-esp32c6 and bme280 , configured zigbee built with esp-idf 5.3.1
build successful , flashed it and while monitoring ( using idf.py monitor) its not clear to me if its crashing
i can't add a zigbee device  in homeassistant , and i can't see any topics in MQTT , looking for xiao/

any pointers ???

and thanks for this ....

**Comment by alexbegoon** [comment]
Hi @jeffbrown57 ,

The monitor is silent, probably because log output is disabled. To enable it, go to the menu:
```sh
idf.py menuconfig
```

Then navigate to , `Component config` → `Log output` → `Default log verbosity`

and set it to `Info`. Save the configuration, build, and flash again with the monitor using:
```sh
idf.py -p <device/port> build flash monitor.
```

You should now see the output. Feel free to ask for help if needed!

**Comment by jeffbrown57** [comment]
thanks so much , i'll let you know

**Comment by jeffbrown57** [comment]
Thanks so much for your expert assistance , working great this morning !!
